/**
 * marker-contract.ts — single source of truth for the Track 8 Pine→backend
 * marker HMAC canonical-string formats.
 *
 * F-10 (Pass 6 / Track A 2026-05-21): two distinct canonical strings exist in
 * the marker subsystem and they must NEVER drift between the Python emitter
 * (`src/engine/pine_compiler.py`) and the TypeScript verifier
 * (`src/server/services/tradingview-marker-service.ts`):
 *
 *   1. EXPORT signature — embedded in the .pine file at compile time. Proves the
 *      file was generated by THIS backend for THIS (strategy, account) pair.
 *      Canonical form: "{strategyId}|{accountId}|marker_export"
 *
 *   2. WEBHOOK signature — recomputed by the backend on every incoming marker
 *      to authenticate the live bar event.
 *      Canonical form: "{strategyId}|{accountId}|{barTimestamp}|{signal}"
 *
 * Both Python and TypeScript MUST import these helpers; do NOT inline the
 * template string anywhere else. The integration test fixture
 * `tests/marker-contract.contract.test.ts` round-trips a known payload to
 * detect drift.
 *
 * VERSION_TAG is bumped on any breaking change so producer/consumer can
 * fast-fail when versions disagree.
 */

export const MARKER_CONTRACT_VERSION = "v1" as const;

/**
 * Canonical string signed by the per-account HMAC secret at .pine compile
 * time. Pine embeds the resulting hex digest as a literal string in the file.
 * The backend recomputes the same digest when validating a marker download.
 */
export function buildExportCanonical(
  strategyId: string,
  accountId: string,
): string {
  return `${strategyId}|${accountId}|marker_export`;
}

/**
 * HIGH (security-auth-hardening 2026-07-17): `buildExportCanonical` above signs
 * a FIXED string independent of `signal` — the SAME `secret_check` literal is
 * embedded once and reused across ALL THREE alertcondition branches (long/short/
 * exit) in the emitted Pine (see pine_compiler.py `_build_marker_alertcondition`).
 * Because that literal is plaintext in a family-distributed .pine file, anyone
 * who has seen the exported Pine text can forge a POST to
 * /api/tradingview/marker with an ARBITRARY `signal` value (the field the
 * signature never covered) and a fresh `bar_timestamp`, indefinitely — the
 * signature never proved WHICH signal it was originally computed for.
 *
 * This variant binds `signal` into the canonical so the compiler can derive a
 * DISTINCT `secret_check` literal per signal branch (Pine already selects among
 * 3 possibilities via a ternary for the `signal` field itself — this mirrors
 * that same compile-time-fixed-set pattern; Pine still cannot sign
 * `bar_timestamp` at runtime — see the module docstring — so replay protection
 * remains the existing 10-minute bar_timestamp window + unique-index dedupe in
 * tradingview-webhook.ts, unchanged by this addition).
 *
 * Canonical form: "{strategyId}|{accountId}|{signal}|marker_export"
 */
export function buildExportCanonicalV2(
  strategyId: string,
  accountId: string,
  signal: number,
): string {
  return `${strategyId}|${accountId}|${signal}|marker_export`;
}

/**
 * Canonical string signed by the per-account HMAC secret for each live bar
 * marker webhook. Recomputed in `validateHmac()` in tradingview-marker-service.
 */
export function buildWebhookCanonical(
  strategyId: string,
  accountId: string,
  barTimestamp: string,
  signal: number,
): string {
  return `${strategyId}|${accountId}|${barTimestamp}|${signal}`;
}

/**
 * Template fragments — exported as compile-time string literals so callers
 * (e.g. Pine code generators) can pattern-match without re-deriving the
 * format. Do NOT use these to BUILD a canonical string at runtime — use the
 * helpers above so producer and consumer share the exact same join order.
 */
export const MARKER_EXPORT_SUFFIX = "marker_export" as const;
export const MARKER_FIELD_SEPARATOR = "|" as const;
