/**
 * strategy-source-resolver.test.ts
 *
 * Unit tests for src/server/lib/strategy-source-resolver.ts
 *
 * Coverage:
 *   - stripMarketSuffix helper (pure function, no DB)
 *   - Path (a): leader strategy resolved via direct bucket join
 *   - Path (b): variant resolved via concept-strip bucket join
 *   - Path (c): variant resolved via audit_log graduation.market_variant_created
 *   - Path (d): last-resort via audit_log scout.operator_ingested
 *   - Multi-mention buckets return all URLs deduped
 *   - Null return for truly orphan strategy (no path yields a URL)
 *   - getStrategySourceUrls batch resolver
 *   - DB errors handled safely — returns null, never throws
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

// ─── Hoisted mock state ───────────────────────────────────────────────────────
//
// We build a mock that intercepts the chained Drizzle ORM calls:
//   db.select().from().where()
//   db.select().from().innerJoin().where()
//   db.select().from().where().limit()
//
// Each test sets selectResult to control what rows come back.

const mockState = vi.hoisted(() => ({
  // Map from "scenario key" → rows returned by that select call.
  // Keyed by call index so multiple db.select() calls can return distinct data.
  selectCallIndex: 0,
  selectResults: [] as Array<unknown[]>,
  throwOnCallIndex: -1, // if >= 0, throw on that call index
}));

// Fluent chain builder — resolves to the next configured result on await.
function buildChain(callIndex: number): unknown {
  const base = {
    from: (_table: unknown) => base,
    innerJoin: (_table: unknown, _cond: unknown) => base,
    where: (_cond: unknown) => base,
    limit: (_n: number) => base,
    orderBy: (_col: unknown) => base,
    then: (
      resolve: (value: unknown[]) => void,
      reject: (err: unknown) => void,
    ) => {
      if (mockState.throwOnCallIndex === callIndex) {
        reject(new Error("mock_db_error"));
        return;
      }
      const rows = mockState.selectResults[callIndex] ?? [];
      resolve(rows);
    },
  };
  return base;
}

vi.mock("../db/index.js", () => {
  return {
    db: {
      select: vi.fn((_fields?: unknown) => {
        const idx = mockState.selectCallIndex++;
        return buildChain(idx);
      }),
    },
  };
});

vi.mock("../db/schema.js", () => ({
  strategies: { name: "name", id: "id", lifecycleState: "lifecycle_state" },
  strategyPendingBuckets: { id: "id", graduatedStrategyId: "graduated_strategy_id", conceptName: "concept_name" },
  strategyPendingMentions: { sourceUrl: "source_url", bucketId: "bucket_id" },
  auditLog: { action: "action", result: "result", input: "input" },
}));

vi.mock("drizzle-orm", async (importActual) => {
  // We don't actually execute Drizzle SQL — keep eq/inArray/sql as no-ops
  // so the module compiles without a real DB connection.
  const actual = await importActual<typeof import("drizzle-orm")>();
  return {
    ...actual,
    eq: vi.fn((_col: unknown, _val: unknown) => ({ __eq: true })),
    inArray: vi.fn((_col: unknown, _vals: unknown) => ({ __inArray: true })),
    sql: vi.fn((..._args: unknown[]) => ({ __sql: true })),
  };
});

vi.mock("../lib/logger.js", () => ({
  logger: { warn: vi.fn(), info: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

vi.mock("../lib/audit-log-helper.js", () => ({
  insertAuditRowSafe: vi.fn().mockResolvedValue(true),
}));

vi.mock("../lib/metrics-registry.js", () => ({
  strategySourceResolutionTotal: {
    labels: vi.fn().mockReturnValue({ inc: vi.fn() }),
  },
}));

// ─── Import subject AFTER mocks are registered ────────────────────────────────
import {
  stripMarketSuffix,
  getStrategySourceUrl,
  getStrategySourceUrls,
  getAllStrategiesWithUrls,
} from "../lib/strategy-source-resolver.js";

// ─── Helper to reset state between tests ─────────────────────────────────────
beforeEach(() => {
  mockState.selectCallIndex = 0;
  mockState.selectResults = [];
  mockState.throwOnCallIndex = -1;
  vi.clearAllMocks();
});

afterEach(() => {
  mockState.selectCallIndex = 0;
  mockState.selectResults = [];
  mockState.throwOnCallIndex = -1;
});

// ─── stripMarketSuffix ────────────────────────────────────────────────────────

describe("stripMarketSuffix", () => {
  it("strips _mes_15m suffix from standard strategy name", () => {
    expect(stripMarketSuffix("orb_mes_15m")).toBe("orb");
  });

  it("strips _mnq_15m suffix", () => {
    expect(stripMarketSuffix("orb_mnq_15m")).toBe("orb");
  });

  it("strips _mcl_5m suffix", () => {
    expect(stripMarketSuffix("vwap_fade_mcl_5m")).toBe("vwap_fade");
  });

  it("strips market suffix without timeframe token", () => {
    // Name that already embedded timeframe before market: orb_15m_mes
    // (generated by already-symboled archetype path in deriveStrategyName)
    expect(stripMarketSuffix("orb_15m_mes")).toBe("orb_15m");
  });

  it("strips longer concept name with market+timeframe", () => {
    expect(stripMarketSuffix("ema_9_21_pullback_mes_15m")).toBe("ema_9_21_pullback");
  });

  it("returns original name when no market suffix present", () => {
    expect(stripMarketSuffix("orb_failure_reversal")).toBe("orb_failure_reversal");
  });

  it("handles MCL uppercase in suffix (case-insensitive)", () => {
    expect(stripMarketSuffix("orb_MCL_5m")).toBe("orb");
  });

  it("does not corrupt names that contain mes/mnq/mcl mid-concept", () => {
    // e.g. a hypothetical concept that has mes in its body but no market suffix
    expect(stripMarketSuffix("mes_breakout_strategy")).toBe("mes_breakout_strategy");
  });
});

// ─── Path (0): config.metadata.source_url (deepscan17 H-1) ───────────────────

describe("getStrategySourceUrl — path (0) config.metadata.source_url", () => {
  it("resolves the live spec_onboarding library via config.metadata.source_url (no bucket needed)", async () => {
    // Call 0: strategies.select returns id + config with the authoritative URL.
    mockState.selectResults[0] = [
      { id: "spec-uuid", config: { metadata: { source_url: "https://www.youtube.com/watch?v=spec123" } } },
    ];
    // No selectResults[1] — path-0 must short-circuit before any bucket/audit query.
    const result = await getStrategySourceUrl("long_entry_or_short_entry_mes_5m");
    expect(result).toEqual(["https://www.youtube.com/watch?v=spec123"]);
  });

  it("handles an array of source_url values (deduped)", async () => {
    mockState.selectResults[0] = [
      { id: "spec-uuid", config: { metadata: { source_url: ["https://yt.com/a", "https://yt.com/a", "https://yt.com/b"] } } },
    ];
    const result = await getStrategySourceUrl("multi_source_spec_mes_5m");
    expect(result).toEqual(["https://yt.com/a", "https://yt.com/b"]);
  });

  it("falls through to bucket paths when config has no source_url", async () => {
    mockState.selectResults[0] = [{ id: "leader-uuid", config: { metadata: {} } }];
    mockState.selectResults[1] = [{ sourceUrl: "https://yt.com/from-bucket" }];
    const result = await getStrategySourceUrl("legacy_bucket_mes_15m");
    expect(result).toContain("https://yt.com/from-bucket");
  });
});

// ─── Path (a): direct bucket join for leader strategy ────────────────────────

describe("getStrategySourceUrl — path (a) direct bucket", () => {
  it("returns URLs when strategy is the leader with direct bucket linkage", async () => {
    // Call 0: strategies.select → return strategy row with id
    mockState.selectResults[0] = [{ id: "strategy-uuid-leader" }];
    // Call 1: bucket+mentions join via graduated_strategy_id → returns URLs
    mockState.selectResults[1] = [
      { sourceUrl: "https://www.youtube.com/watch?v=abc123" },
      { sourceUrl: "https://www.youtube.com/watch?v=def456" },
    ];

    const result = await getStrategySourceUrl("orb_mes_15m");

    expect(result).not.toBeNull();
    expect(result).toContain("https://www.youtube.com/watch?v=abc123");
    expect(result).toContain("https://www.youtube.com/watch?v=def456");
    expect(result!.length).toBe(2);
  });

  it("deduplicates URLs when multiple mentions point to same source", async () => {
    mockState.selectResults[0] = [{ id: "strategy-uuid-leader" }];
    mockState.selectResults[1] = [
      { sourceUrl: "https://www.youtube.com/watch?v=abc123" },
      { sourceUrl: "https://www.youtube.com/watch?v=abc123" }, // duplicate
      { sourceUrl: "https://www.youtube.com/watch?v=def456" },
    ];

    const result = await getStrategySourceUrl("orb_mes_15m");

    expect(result!.length).toBe(2);
    expect(new Set(result!).size).toBe(2);
  });
});

// ─── Path (b): variant concept-strip inheritance ──────────────────────────────

describe("getStrategySourceUrl — path (b) variant concept-strip", () => {
  it("returns URLs for variant strategy via concept-strip bucket join", async () => {
    // Call 0: strategy lookup → found
    mockState.selectResults[0] = [{ id: "strategy-uuid-variant-mnq" }];
    // Call 1: path (a) direct bucket → empty (this is a variant, not a leader)
    mockState.selectResults[1] = [];
    // Call 2: path (b) concept-strip bucket join → returns URLs from leader's bucket
    mockState.selectResults[2] = [
      { sourceUrl: "https://www.youtube.com/watch?v=leader-video" },
    ];

    const result = await getStrategySourceUrl("orb_mnq_15m");

    expect(result).not.toBeNull();
    expect(result).toContain("https://www.youtube.com/watch?v=leader-video");
  });

  it("falls through to next path when concept-strip finds no bucket", async () => {
    mockState.selectResults[0] = [{ id: "strategy-uuid-variant" }];
    mockState.selectResults[1] = []; // path (a) empty
    mockState.selectResults[2] = []; // path (b) empty
    // path (c): audit_log graduation.market_variant_created
    mockState.selectResults[3] = [
      {
        result: {
          variant_name: "vwap_fade_mcl_5m",
          leader_strategy_id: "leader-uuid",
          variant_market: "MCL",
        },
      },
    ];
    // path (c) inner: resolve leader via direct bucket
    mockState.selectResults[4] = [
      { sourceUrl: "https://www.youtube.com/watch?v=from-audit" },
    ];

    const result = await getStrategySourceUrl("vwap_fade_mcl_5m");

    expect(result).not.toBeNull();
    expect(result).toContain("https://www.youtube.com/watch?v=from-audit");
  });
});

// ─── Path (c): audit_log graduation.market_variant_created ───────────────────

describe("getStrategySourceUrl — path (c) audit fallback", () => {
  it("resolves via graduation audit when no bucket linkage exists", async () => {
    mockState.selectResults[0] = [{ id: "strategy-uuid-variant" }];
    mockState.selectResults[1] = []; // path (a) empty
    mockState.selectResults[2] = []; // path (b) empty
    // path (c) audit query
    mockState.selectResults[3] = [
      {
        result: {
          variant_name: "orb_mcl_5m",
          leader_strategy_id: "leader-uuid-123",
        },
      },
    ];
    // inner path (a) on leader
    mockState.selectResults[4] = [
      { sourceUrl: "https://www.youtube.com/watch?v=orb-original" },
    ];

    const result = await getStrategySourceUrl("orb_mcl_5m");

    expect(result).not.toBeNull();
    expect(result).toContain("https://www.youtube.com/watch?v=orb-original");
  });
});

// ─── Path (d): scout.operator_ingested audit fallback ────────────────────────

describe("getStrategySourceUrl — path (d) scout audit fallback", () => {
  it("resolves via scout ingestion audit as last resort", async () => {
    mockState.selectResults[0] = [{ id: "strategy-uuid-edge-case" }];
    mockState.selectResults[1] = []; // path (a) empty
    mockState.selectResults[2] = []; // path (b) empty
    mockState.selectResults[3] = []; // path (c) audit empty
    // path (d) scout audit
    mockState.selectResults[4] = [
      {
        input: {
          url: "https://www.youtube.com/watch?v=manual-ingest",
          video_id: "manual-ingest",
          title: "ORB Strategy Tutorial",
        },
        result: { ideas: [{ idea_name: "orb_5m" }] },
      },
    ];

    const result = await getStrategySourceUrl("orb_5m_mes");

    expect(result).not.toBeNull();
    expect(result).toContain("https://www.youtube.com/watch?v=manual-ingest");
  });
});

// ─── Null for orphan strategy ─────────────────────────────────────────────────

describe("getStrategySourceUrl — null for orphan", () => {
  it("returns null when no path yields a URL", async () => {
    // Strategy not found in strategies table (or found but no bucket/audit links)
    mockState.selectResults[0] = []; // strategy not found
    mockState.selectResults[1] = []; // path (b) empty
    mockState.selectResults[2] = []; // path (c) empty
    mockState.selectResults[3] = []; // path (d) empty

    const result = await getStrategySourceUrl("orphan_strategy_mes_15m");

    expect(result).toBeNull();
  });

  it("returns null when strategy id is found but all paths return empty", async () => {
    mockState.selectResults[0] = [{ id: "strategy-uuid-no-sources" }];
    mockState.selectResults[1] = []; // path (a) empty
    mockState.selectResults[2] = []; // path (b) empty
    mockState.selectResults[3] = []; // path (c) empty
    mockState.selectResults[4] = []; // path (d) empty

    const result = await getStrategySourceUrl("no_source_mes_15m");

    expect(result).toBeNull();
  });
});

// ─── Error safety ─────────────────────────────────────────────────────────────

describe("getStrategySourceUrl — error safety", () => {
  it("returns null when the strategy lookup DB call throws", async () => {
    // Throw on call index 0 (strategy lookup)
    mockState.throwOnCallIndex = 0;

    const result = await getStrategySourceUrl("orb_mes_15m");

    expect(result).toBeNull();
  });
});

// ─── getStrategySourceUrls batch ─────────────────────────────────────────────

describe("getStrategySourceUrls", () => {
  it("returns empty record for empty input", async () => {
    const result = await getStrategySourceUrls([]);
    expect(result).toEqual({});
  });

  it("returns resolved strategy URL for a single strategy via path (a)", async () => {
    // Single strategy so there is no parallel interleaving of call indices.
    mockState.selectResults[0] = [{ id: "uuid-single" }];
    mockState.selectResults[1] = [{ sourceUrl: "https://yt.com/orb-batch" }];

    const result = await getStrategySourceUrls(["orb_mes_15m"]);

    expect(result["orb_mes_15m"]).toContain("https://yt.com/orb-batch");
  });

  it("returns empty array for unresolved strategy", async () => {
    // Strategy not in DB; all paths return empty.
    mockState.selectResults[0] = []; // strategy lookup empty
    mockState.selectResults[1] = []; // path-b empty
    mockState.selectResults[2] = []; // path-c empty
    mockState.selectResults[3] = []; // path-d empty

    const result = await getStrategySourceUrls(["orphan_mes_15m"]);

    expect(result["orphan_mes_15m"]).toEqual([]);
  });
});

// ─── getAllStrategiesWithUrls ─────────────────────────────────────────────────

describe("getAllStrategiesWithUrls", () => {
  it("returns array with name and urls for a single resolved strategy", async () => {
    // getAllStrategiesWithUrls: call 0 = fetch all strategy names.
    // Single strategy to avoid parallel call-index interleaving.
    mockState.selectResults[0] = [{ name: "orb_mes_15m" }];
    // Resolution of orb_mes_15m: lookup (1), path-a direct (2).
    mockState.selectResults[1] = [{ id: "uuid-leader" }];
    mockState.selectResults[2] = [{ sourceUrl: "https://yt.com/orb-all" }];

    const result = await getAllStrategiesWithUrls();

    expect(Array.isArray(result)).toBe(true);
    expect(result.length).toBe(1);
    expect(result[0]?.urls).toContain("https://yt.com/orb-all");
  });

  it("returns empty array on DB error without throwing", async () => {
    mockState.throwOnCallIndex = 0;

    const result = await getAllStrategiesWithUrls();

    expect(result).toEqual([]);
  });
});
