"""H1 Wave-4 pilot conveyor runner (pilot pre-reg `docs/designs/h1-pilot-
preregistration-2026-07-12.md`, addendum-aware).

Deterministic GLUE that drives, per video:
  transcript -> tier-1 detection -> tier-1 fall-through spans ->
  blind tier-3 packets (leak-scanned BEFORE dispatch) ->
  [external adjudication, NOT this module] ->
  assemble_certificate -> pilot-grade certificate

TWO-PHASE DESIGN (the structural proof this module never adjudicates):
  - `prepare_video(...)`  runs tier-1, collects fall-throughs, builds a
    blind tier-3 packet (Wave-1 shape), runs the blinding leak-scan, and
    REFUSES to return a packet that fails it (raises `LeakScanFailure`).
    Nothing in this phase calls an LLM or agent.
  - `finalize_certificate(...)` accepts `Tier3Verdict` objects fed back in
    by the caller (the parent's job -- dispatching blind fresh-context
    adjudicators, mirroring the Wave-1 shakedown protocol, is OUTSIDE this
    module by design) and calls `cert_assembler.assemble_certificate`,
    which itself never performs I/O or calls an LLM (see that module's
    docstring). This module inherits that contract: it contains no local-
    inference client, no cloud-model SDK, and no outbound HTTP call of any
    kind anywhere on the prepare/finalize path (test_pilot_conveyor.py
    asserts this by source scan, deliberately not spelled out by name
    here so this sentence cannot itself trip that scan).
  - `aggregate(...)` reduces a list of certificates to the pilot §1
    read: cert-grade fraction + mean tier-3 adjudications/video.

LEAK-SCAN REUSE DISPOSITION: PARITY-FIXTURED against
`docs/designs/h1-wave1-shakedown-packets-2026-07-12.json`'s own
`blinding_contract` clause ("exposes ZERO outcome/tally/verdict/
rationale... no demotion label, no DRI, no counts, no class distribution,
no which-items-are-controls marking") -- no importable Python leak-scan
function exists anywhere in this repo (the Wave-1 packets were hand-built
JSON, not generated by checked-in code), so `blinding_leak_scan` below is
new code that encodes the same forbidden-field contract, structurally (an
allowlist of rater-facing keys) AND lexically (a forbidden-token scan over
the rater-facing `sections` content only -- the top-level `blinding_
contract`/`instructions` meta text is EXCLUDED from the token scan because
it legitimately CONTAINS the forbidden words as its own description of the
policy; scanning it would be a false-positive self-trip, exactly the kind
of "verify the alarm instrument first" trap the campaign's tripwire law
warns about).

CONTROL SET REUSE (REUSED, not reinvented): the pilot's tier-3 Set-A
control-gate calibration items are the SAME 10 Wave-1 items (`h1-wave1-
shakedown-packets-2026-07-12.json`, section `SET-A`), loaded verbatim.
Those items are content-agnostic calibration exemplars (generic
unambiguous-gate / unambiguous-narration text), not specific to any one
video, so reusing them for every pilot video's control gate is the
faithful continuation of the SAME protocol -- deriving a NEW control set
per sealed video would be new-instrument judgment (deciding what counts as
an unambiguous control item) and is explicitly OUT OF SCOPE for this glue
build (see NEW-INSTRUMENT-LOGIC flag below). The private answer key
(`h1-wave1-shakedown-answerkey-2026-07-12.json`) is NEVER loaded here --
only the verifier holds it; `control_gate_passed` on each `Tier3Verdict`
is computed by the CALLER (the real dispatcher, against that key) and
consumed here as data, same as `cert_assembler.py` already does.

TRANSCRIPT FETCH SEAM: `fetch_transcript` is deliberately NOT implemented.
The production path is Node/TS (`fetchTranscriptWithRetry` in
`src/server/services/transcript-fetch-queue.ts`, wrapping the
`youtube-transcript` npm package + Google YouTube Data API v3 for
metadata, CLAUDE.md §2b) -- a CROSS-LANGUAGE seam from this Python module,
not a same-language reuse. Wave 9 (2026-05-17) removed ScrapingBee /
Supadata / ScrapingDog; do not reintroduce any VPN/scraper path here.

NEW-INSTRUMENT-LOGIC FLAGS (glue, not judgment, but named for review):
  1. Sentence-boundary segmentation (`_segment_transcript`) is a
     MECHANICAL punctuation split used to route transcript text into
     `tier1_detectors.run_tier1` per call -- it decides NO gate-strength/
     context semantics, only where one detector call ends and the next
     begins. If the real pilot's upstream extractor already produces
     condition-level quote boundaries (as the frozen 143/78 corpus does),
     THAT boundary source should replace this one; this fallback exists
     only because a raw sealed transcript has no such boundaries yet.
  2. `verdict_from_rater_response` copies a rater's single `role` answer
     into BOTH `Tier3Verdict.surface_class` and `Tier3Verdict.verdict`
     (cert_assembler.py documents these as related-but-separate fields).
     This is a straight field copy, not a new scoring rule; a richer
     dispatcher may supply a more specific `surface_class` directly via
     `Tier3Verdict(...)` instead of this helper.
Neither flag changes what any lint or grade means -- both are routing,
not measurement -- but they are named here per the campaign's tripwire
discipline rather than left implicit.

NO vectorbt / backtester import anywhere in this module (CLAUDE.md's
pytest-collection JIT-hang caveat) -- it only imports the pure-stdlib
extraction package, matching `cert_assembler.py` / `tier1_detectors.py`.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from .cert_assembler import ConditionTopology, Tier3Verdict, assemble_certificate
from .tier1_detectors import Tier1Detection, Tier1FallThrough, run_tier1

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
_WAVE1_PACKETS_PATH = os.path.join(
    _ROOT, "docs", "designs", "h1-wave1-shakedown-packets-2026-07-12.json"
)

# --------------------------------------------------------------------------- #
# Segmentation (routing only -- see module docstring NEW-INSTRUMENT-LOGIC #1)
# --------------------------------------------------------------------------- #

_SENTENCE_RE = re.compile(r"[^.!?]+[.!?]*")


def _segment_transcript(text: str) -> List[Tuple[int, int]]:
    """Mechanical sentence-boundary split, returning [start,end) spans into
    `text` with surrounding whitespace trimmed. Empty/whitespace-only
    fragments are dropped. Deterministic, no judgment about content."""
    spans: List[Tuple[int, int]] = []
    for m in _SENTENCE_RE.finditer(text):
        s, e = m.start(), m.end()
        seg = text[s:e]
        lstripped = seg.lstrip()
        if not lstripped.strip():
            continue
        lead = len(seg) - len(lstripped)
        s2 = s + lead
        rstripped = text[s2:e].rstrip()
        e2 = s2 + len(rstripped)
        if s2 < e2:
            spans.append((s2, e2))
    return spans


# --------------------------------------------------------------------------- #
# Blinding leak-scan (PARITY-FIXTURED against the Wave-1 blinding_contract)
# --------------------------------------------------------------------------- #

_ALLOWED_ITEM_KEYS = {
    "item_id",
    "video_id",
    "concept_id",
    "family",
    "timeframe",
    "extracted_condition_type",
    "extracted_object",
    "quote_anchor",
    "needs_dual_anchor",
    "english_gloss",
    "rater_response",
}
_ALLOWED_RATER_RESPONSE_KEYS = {"role", "notes"}
_ALLOWED_QUOTE_ANCHOR_KEYS = {"language", "verbatim"}

# Lexical scan target: forbidden anywhere in the rater-facing `sections`
# content (items). Deliberately NOT scanned against the top-level
# `blinding_contract`/`instructions` meta text -- that text legitimately
# NAMES these words as the policy it enforces (see module docstring).
_FORBIDDEN_TOKENS = (
    "demotion",
    "dri",
    "verdict",
    "rationale",
    "tally",
    "outcome",
    "class_distribution",
    "is_control",
    "control_answer",
    "answer_key",
    "ground_truth",
    "gold_label",
    "expected_role",
    "correct_role",
    "control_gate_item_ids",
)


@dataclass
class LeakScanResult:
    clean: bool
    violations: List[str] = field(default_factory=list)


class LeakScanFailure(Exception):
    def __init__(self, video_id: str, violations: List[str]):
        self.video_id = video_id
        self.violations = violations
        super().__init__(f"blinding leak-scan FAILED for video={video_id}: {violations}")


def blinding_leak_scan(packet: dict) -> LeakScanResult:
    """House-standard leak-scan, run BEFORE any tier-3 packet is dispatched
    (pilot pre-reg §3). Two independent checks, either of which can fire:

      1. STRUCTURAL: every item in every `sections[*].items` entry, its
         `rater_response`, and its `quote_anchor` must use ONLY the
         allowlisted keys, and `rater_response.role`/`.notes` must both be
         null (a pre-filled answer is itself a leak).
      2. LEXICAL: none of `_FORBIDDEN_TOKENS` may appear (case-insensitive)
         anywhere in the serialized `sections` content.

    Silent (clean=True, violations=[]) on a packet with neither. Fires
    (clean=False) on either. Never raises -- callers decide whether to
    refuse emission (`prepare_video` does)."""
    violations: List[str] = []

    serialized = json.dumps(packet.get("sections", []), default=str).lower()
    for tok in _FORBIDDEN_TOKENS:
        if tok in serialized:
            violations.append(f"forbidden_token:{tok}")

    for section in packet.get("sections", []):
        for item in section.get("items", []):
            item_id = item.get("item_id", "<unknown>")
            extra = set(item.keys()) - _ALLOWED_ITEM_KEYS
            if extra:
                violations.append(f"forbidden_item_keys:{item_id}:{sorted(extra)}")
            rr = item.get("rater_response")
            if isinstance(rr, dict):
                extra_rr = set(rr.keys()) - _ALLOWED_RATER_RESPONSE_KEYS
                if extra_rr:
                    violations.append(f"forbidden_rater_response_keys:{item_id}:{sorted(extra_rr)}")
                if rr.get("role") is not None or rr.get("notes") is not None:
                    violations.append(f"prefilled_rater_response:{item_id}")
            qa = item.get("quote_anchor")
            if isinstance(qa, dict):
                extra_qa = set(qa.keys()) - _ALLOWED_QUOTE_ANCHOR_KEYS
                if extra_qa:
                    violations.append(f"forbidden_quote_anchor_keys:{item_id}:{sorted(extra_qa)}")

    return LeakScanResult(clean=not violations, violations=violations)


# --------------------------------------------------------------------------- #
# Tier-3 packet assembly (Wave-1 shape, Set-A REUSED verbatim)
# --------------------------------------------------------------------------- #


def _load_wave1_control_section() -> Tuple[dict, str, dict, dict]:
    """Load the REUSED Set-A control section + shared meta text from the
    real Wave-1 packets artifact. Never touches the answer key (verifier-
    only, per that file's own audience note)."""
    d = json.load(open(_WAVE1_PACKETS_PATH, encoding="utf-8"))
    for section in d["sections"]:
        if section["section_id"] == "SET-A":
            return section, d["blinding_contract"], d["closed_taxonomy"], d["instructions"]
    raise RuntimeError(f"SET-A control section not found in {_WAVE1_PACKETS_PATH}")


def _build_tier3_packet(
    full_transcript: str,
    video_id: str,
    fallthroughs: List[Tier1FallThrough],
) -> Tuple[dict, Dict[str, Tuple[int, int]]]:
    """Build one blind tier-3 packet for `video_id`: REUSED Set-A controls +
    a fresh Set-B built from this video's tier-1 fall-through spans. Returns
    (packet, item_span_map) -- the span map is INTERNAL bookkeeping (join
    key for `finalize_certificate`), never placed inside the packet itself
    (char_span is not something a blind rater needs, and keeping it out of
    the rater-facing artifact keeps the leak-scan's allowlist simple)."""
    set_a, blinding_contract, closed_taxonomy, instructions = _load_wave1_control_section()

    target_items: List[dict] = []
    item_span_map: Dict[str, Tuple[int, int]] = {}
    for i, ft in enumerate(fallthroughs):
        item_id = f"{video_id}-B{i:03d}"
        s, e = ft.char_span
        item_span_map[item_id] = (s, e)
        target_items.append(
            {
                "item_id": item_id,
                "video_id": video_id,
                "family": None,
                "timeframe": None,
                "extracted_condition_type": None,
                "extracted_object": None,
                "quote_anchor": {"language": "en", "verbatim": full_transcript[s:e]},
                "rater_response": {"role": None, "notes": None},
            }
        )

    packet = {
        "artifact": "h1-pilot-tier3-packet",
        "version": "2026-07-12",
        "purpose": f"Pilot tier-3 blind adjudication packet, video={video_id}.",
        "blinding_contract": blinding_contract,
        "closed_taxonomy": closed_taxonomy,
        "instructions": instructions,
        "counts": {"control_items": set_a["item_count"], "target_items": len(target_items)},
        "sections": [
            set_a,
            {
                "section_id": "SET-B",
                "concept_id": None,
                "label": f"Set B -- video {video_id} tier-1 fall-through targets "
                "(complete AFTER Set A + control-gate)",
                "item_count": len(target_items),
                "items": target_items,
            },
        ],
    }
    return packet, item_span_map


# --------------------------------------------------------------------------- #
# Transcript fetch seam (production path documented, NOT implemented here)
# --------------------------------------------------------------------------- #


def fetch_transcript(video_id: str) -> str:  # pragma: no cover - seam only
    """SEAM. Deliberately unimplemented -- glue only, per the Wave-4 brief.

    PRODUCTION PATH (cross-language from this Python module):
      `fetchTranscriptWithRetry(videoId)` in
      `src/server/services/transcript-fetch-queue.ts`, which wraps the
      `youtube-transcript` npm package (+ Google YouTube Data API v3 for
      title/metadata search where needed, CLAUDE.md §2b). Wave 9
      (2026-05-17) removed ScrapingBee / Supadata / ScrapingDog -- do NOT
      reintroduce any VPN/scraper path here or in whatever wires this seam.

    The real pilot run wires this to that Node service (subprocess or HTTP
    bridge; deciding which is itself a small integration task, out of scope
    for this glue build) BEFORE any sealed video's transcript is fetched.
    Raising here (instead of silently returning an empty string) means a
    caller can never accidentally certify an empty transcript."""
    raise NotImplementedError(
        "fetch_transcript is an unwired SEAM. Production path: "
        "fetchTranscriptWithRetry() in src/server/services/transcript-fetch-queue.ts "
        "(youtube-transcript npm + YouTube Data API v3, CLAUDE.md §2b). "
        f"video_id={video_id!r} was not fetched."
    )


# --------------------------------------------------------------------------- #
# Phase 1: prepare_video
# --------------------------------------------------------------------------- #


def prepare_video(
    transcript_text: str,
    video_id: str,
    extractor_version: str,
    taxonomy_version: str,
    full_transcript_sha256: Optional[str] = None,
) -> dict:
    """Phase 1 (never calls an LLM/agent): tier-1 detection -> fall-through
    collection -> blind tier-3 packet -> leak-scan gate. Raises
    `LeakScanFailure` and returns NOTHING usable if the packet fails the
    scan -- the caller must never dispatch a refused packet."""
    if full_transcript_sha256 is None:
        full_transcript_sha256 = hashlib.sha256(transcript_text.encode("utf-8")).hexdigest()

    tier1_detections: List[Tier1Detection] = []
    tier1_fallthroughs: List[Tier1FallThrough] = []
    for s, e in _segment_transcript(transcript_text):
        seg = transcript_text[s:e]
        result = run_tier1(seg, char_span=(s, e))
        tier1_detections.extend(result.detections)
        if result.fallthrough is not None:
            tier1_fallthroughs.append(result.fallthrough)

    packet, item_span_map = _build_tier3_packet(transcript_text, video_id, tier1_fallthroughs)
    scan = blinding_leak_scan(packet)
    if not scan.clean:
        raise LeakScanFailure(video_id=video_id, violations=scan.violations)

    return {
        "video_id": video_id,
        "full_transcript": transcript_text,
        "tier1_detections": tier1_detections,
        "tier1_fallthroughs": tier1_fallthroughs,
        "tier3_packet": packet,
        "item_span_map": item_span_map,
        "leak_scan": scan,
        "provenance": {
            "source_video_id": video_id,
            "full_transcript_sha256": full_transcript_sha256,
            "extractor_version": extractor_version,
            "taxonomy_version": taxonomy_version,
        },
    }


# --------------------------------------------------------------------------- #
# Rater-response -> Tier3Verdict helper (see NEW-INSTRUMENT-LOGIC #2)
# --------------------------------------------------------------------------- #


def verdict_from_rater_response(
    char_span: Tuple[int, int],
    quote_anchor: str,
    role: str,
    control_gate_passed: bool,
) -> Tier3Verdict:
    """Straight field-copy from a blind rater's closed-taxonomy `role`
    answer into a `Tier3Verdict` (surface_class == verdict == role). A
    richer dispatcher may construct `Tier3Verdict` directly instead."""
    return Tier3Verdict(
        char_span=char_span,
        quote_anchor=quote_anchor,
        surface_class=role,
        verdict=role,
        control_gate_passed=control_gate_passed,
    )


# --------------------------------------------------------------------------- #
# Phase 2: finalize_certificate
# --------------------------------------------------------------------------- #


def finalize_certificate(
    prepare_output: dict,
    tier3_verdicts: List[Tier3Verdict],
    topology: Optional[List[ConditionTopology]] = None,
    or_branches: Optional[List[List[str]]] = None,
    scope_line: Optional[str] = None,
    dry_run: bool = False,
) -> dict:
    """Phase 2 (never calls an LLM/agent -- `tier3_verdicts` are consumed as
    DATA, same contract as `cert_assembler.assemble_certificate` itself).
    Joins verdicts to fall-through spans by char_span (via `Tier3Verdict.
    char_span`, exactly as `assemble_certificate` already does internally)
    and returns the pilot-grade certificate. `dry_run=True` stamps a loud
    `dry_run` marker (top-level AND inside `provenance`) so no synthetic
    certificate can be mistaken for a real one."""
    prov = prepare_output["provenance"]
    cert = assemble_certificate(
        full_transcript=prepare_output["full_transcript"],
        full_transcript_sha256=prov["full_transcript_sha256"],
        source_video_id=prov["source_video_id"],
        extractor_version=prov["extractor_version"],
        taxonomy_version=prov["taxonomy_version"],
        tier1_detections=prepare_output["tier1_detections"],
        tier1_fallthroughs=prepare_output["tier1_fallthroughs"],
        tier3_verdicts=tier3_verdicts,
        topology=topology,
        or_branches=or_branches,
        scope_line=scope_line,
    )
    cert["dry_run"] = dry_run
    cert["provenance"]["dry_run"] = dry_run
    return cert


# --------------------------------------------------------------------------- #
# aggregate
# --------------------------------------------------------------------------- #


def aggregate(certificates: List[dict]) -> dict:
    """Pilot §1 read: cert-grade fraction (pilot_grade True / N) + mean
    tier-3 adjudications/video (against the §1 ~5-9 expected range / ~15
    affordability ceiling -- this function only measures, the ceiling
    comparison is a caller/report-level read, not a gate here)."""
    n = len(certificates)
    pilot_grade_n = sum(1 for c in certificates if c.get("pilot_grade"))
    full_grade_n = sum(1 for c in certificates if c.get("full_grade"))
    adjudications_per_video = [
        sum(1 for cond in c["conditions"] if cond.get("classifying_tier") == 3)
        for c in certificates
    ]
    return {
        "n_videos": n,
        "pilot_grade_n": pilot_grade_n,
        "pilot_grade_fraction": round(pilot_grade_n / n, 4) if n else None,
        "full_grade_n": full_grade_n,
        "tier3_adjudications_per_video": adjudications_per_video,
        "mean_tier3_adjudications_per_video": (
            round(sum(adjudications_per_video) / n, 4) if n else None
        ),
    }


# --------------------------------------------------------------------------- #
# DRY-RUN proof (SYNTHETIC transcript, non-sealed -- see module constraints)
# --------------------------------------------------------------------------- #

# Sentences lifted verbatim from src/engine/extraction/fixtures/
# tier1_birth_fixtures.json's own confirmed positive/negative fixtures
# (conditional-action, exclusion-contrast, imperative, plus two confirmed
# tier-1-SILENT sentences -- one the named walkthrough-narration ambiguity
# class, one clean context/narration) -- NOT the sealed 16, NOT any real
# fresh transcript.
DRY_RUN_VIDEO_ID = "DRY-RUN-synthetic-v1"
DRY_RUN_TRANSCRIPT = (
    "Buy from the demand zone when it is retested. "
    "We do have a fair value gap here where price tapped the level before. "
    "Take puts on a VWOP retest, NOT a pre-market low retest. "
    "Set your stop at the low of the hammer. "
    "Now back to the euro dollar chart here."
)


def run_dry_run() -> dict:
    """Runs the FULL prepare -> [synthetic verdicts] -> finalize loop on
    `DRY_RUN_TRANSCRIPT`. Also proves the leak-scan actually gates (fires on
    an injected forbidden token, silent on the real clean packet) as part
    of the same call, per the brief's "prove it fires" requirement. Returns
    a dict a caller can json.dump straight to a DRY-RUN-labeled file."""
    prep = prepare_video(
        transcript_text=DRY_RUN_TRANSCRIPT,
        video_id=DRY_RUN_VIDEO_ID,
        extractor_version="pilot-conveyor-dry-run-v1",
        taxonomy_version="h1-pilot-2026-07-12",
    )

    # Positive leak-scan proof: poison a COPY of the real packet and confirm
    # the scan fires (fires-on-positive). The real packet already cleared
    # the scan inside prepare_video (silent-on-negative) or this call would
    # have raised LeakScanFailure already.
    poisoned = json.loads(json.dumps(prep["tier3_packet"]))
    poisoned["sections"][-1]["items"][0]["demotion_role_5class"] = "OPTIONAL"
    positive_scan = blinding_leak_scan(poisoned)
    assert not positive_scan.clean, "leak-scan birth-gate: FAILED to fire on an injected leak"
    assert prep["leak_scan"].clean, "leak-scan birth-gate: the real dry-run packet was not clean"

    # Synthetic Tier3Verdicts for every fall-through span -- a REHEARSAL, no
    # real adjudicator involved (no LLM/agent call anywhere in this
    # function). One span gets "context" (the clean narration sentence),
    # one gets "gate-strength" (the ambiguity-class sentence, treated here
    # as a stand-in adjudicated call, not a claim about its true label).
    verdicts: List[Tier3Verdict] = []
    for i, ft in enumerate(prep["tier1_fallthroughs"]):
        role = "context" if i % 2 == 0 else "gate-strength"
        verdicts.append(
            verdict_from_rater_response(
                char_span=ft.char_span,
                quote_anchor=DRY_RUN_TRANSCRIPT[ft.char_span[0] : ft.char_span[1]],
                role=role,
                control_gate_passed=True,
            )
        )

    cert = finalize_certificate(prep, verdicts, dry_run=True)

    return {
        "artifact": "h1-pilot-conveyor-DRY-RUN",
        "dry_run": True,
        "video_id": DRY_RUN_VIDEO_ID,
        "prepare_leak_scan": {"clean": prep["leak_scan"].clean, "violations": prep["leak_scan"].violations},
        "leak_scan_positive_proof": {
            "clean": positive_scan.clean,
            "violations": positive_scan.violations,
        },
        "certificate": cert,
    }


def write_dry_run_artifact(result: dict, out_dir: str) -> str:
    """Writes `result` (from `run_dry_run`) to a filename that ALWAYS
    contains "DRY-RUN" -- non-negotiable per the pilot brief, so no future
    reader can mistake a synthetic certificate for a real one. Returns the
    written path."""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"h1-pilot-DRY-RUN-cert-{result['video_id']}.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2, default=str)
    return path


def main() -> None:  # pragma: no cover - manual invocation
    result = run_dry_run()
    out_dir = os.path.join(_ROOT, "docs", "replay-results", "h1-scripts", "dry-run-output")
    path = write_dry_run_artifact(result, out_dir)
    cert = result["certificate"]
    print(f"DRY-RUN certificate written: {path}")
    print(f"  pilot_grade={cert['pilot_grade']}  full_grade={cert['full_grade']}  dry_run={cert['dry_run']}")
    print(f"  leak_scan clean(prepare)={result['prepare_leak_scan']['clean']}  "
          f"fires_on_positive={not result['leak_scan_positive_proof']['clean']}")


if __name__ == "__main__":  # pragma: no cover
    main()
