-- Strategy Names: unique codename pool for Forge-named strategies
-- Each TIER_1 strategy gets a "Forge {Codename}" name, never recycled

CREATE TABLE IF NOT EXISTS strategy_names (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codename TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL UNIQUE,
  strategy_id UUID REFERENCES strategies(id),
  claimed BOOLEAN DEFAULT FALSE,
  claimed_at TIMESTAMPTZ,
  retired BOOLEAN DEFAULT FALSE,
  retired_at TIMESTAMPTZ,
  version TEXT DEFAULT 'v1.0',
  origin_class TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS strategy_names_claimed_idx ON strategy_names (claimed);
CREATE INDEX IF NOT EXISTS strategy_names_strategy_id_idx ON strategy_names (strategy_id);

-- Seed 200 codenames (all unclaimed)
INSERT INTO strategy_names (id, codename, full_name, claimed, retired, created_at)
VALUES
    (gen_random_uuid(), 'Viper', 'Forge Viper', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Phantom', 'Forge Phantom', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Tide', 'Forge Tide', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Raid', 'Forge Raid', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Apex', 'Forge Apex', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Serpent', 'Forge Serpent', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Shadow', 'Forge Shadow', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Fracture', 'Forge Fracture', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Thrust', 'Forge Thrust', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Origin', 'Forge Origin', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Atlas', 'Forge Atlas', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Judas', 'Forge Judas', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Shield', 'Forge Shield', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Unicorn', 'Forge Unicorn', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Mirror', 'Forge Mirror', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Sniper', 'Forge Sniper', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Pulse', 'Forge Pulse', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Trigger', 'Forge Trigger', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Quake', 'Forge Quake', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Falcon', 'Forge Falcon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Havoc', 'Forge Havoc', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Eclipse', 'Forge Eclipse', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Bolt', 'Forge Bolt', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Drift', 'Forge Drift', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Fang', 'Forge Fang', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Cipher', 'Forge Cipher', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Onyx', 'Forge Onyx', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Prism', 'Forge Prism', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Vertex', 'Forge Vertex', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Nova', 'Forge Nova', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Storm', 'Forge Storm', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Razor', 'Forge Razor', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Ember', 'Forge Ember', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Wraith', 'Forge Wraith', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Halo', 'Forge Halo', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Torque', 'Forge Torque', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Flux', 'Forge Flux', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Zenith', 'Forge Zenith', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Spectre', 'Forge Spectre', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Aegis', 'Forge Aegis', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Blitz', 'Forge Blitz', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Chrono', 'Forge Chrono', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Delta', 'Forge Delta', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Edge', 'Forge Edge', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Flare', 'Forge Flare', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Granite', 'Forge Granite', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Hydra', 'Forge Hydra', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Ion', 'Forge Ion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Jolt', 'Forge Jolt', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Krypton', 'Forge Krypton', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Lancer', 'Forge Lancer', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Mammoth', 'Forge Mammoth', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Nexus', 'Forge Nexus', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Orion', 'Forge Orion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Pike', 'Forge Pike', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Raven', 'Forge Raven', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Saber', 'Forge Saber', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Talon', 'Forge Talon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Ultra', 'Forge Ultra', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Vector', 'Forge Vector', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Warden', 'Forge Warden', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Anvil', 'Forge Anvil', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Bravo', 'Forge Bravo', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Cobalt', 'Forge Cobalt', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Dagger', 'Forge Dagger', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Epoch', 'Forge Epoch', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Forge', 'Forge Forge', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Glyph', 'Forge Glyph', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Hawk', 'Forge Hawk', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Inferno', 'Forge Inferno', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Javelin', 'Forge Javelin', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Karma', 'Forge Karma', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Lynx', 'Forge Lynx', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Mantis', 'Forge Mantis', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Nimbus', 'Forge Nimbus', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Obsidian', 'Forge Obsidian', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Patriot', 'Forge Patriot', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Quasar', 'Forge Quasar', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Raptor', 'Forge Raptor', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Sigma', 'Forge Sigma', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Tempest', 'Forge Tempest', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Umbra', 'Forge Umbra', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Venom', 'Forge Venom', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Wolf', 'Forge Wolf', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Xenon', 'Forge Xenon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Yeti', 'Forge Yeti', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Zephyr', 'Forge Zephyr', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Archer', 'Forge Archer', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Bandit', 'Forge Bandit', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Centurion', 'Forge Centurion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Draco', 'Forge Draco', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Electra', 'Forge Electra', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Fury', 'Forge Fury', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Goliath', 'Forge Goliath', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Hermes', 'Forge Hermes', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Impulse', 'Forge Impulse', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Jinx', 'Forge Jinx', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Knight', 'Forge Knight', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Legion', 'Forge Legion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Mirage', 'Forge Mirage', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Nomad', 'Forge Nomad', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Omega', 'Forge Omega', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Phoenix', 'Forge Phoenix', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Quantum', 'Forge Quantum', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Ronin', 'Forge Ronin', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Sentinel', 'Forge Sentinel', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Titan', 'Forge Titan', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Valor', 'Forge Valor', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Warlock', 'Forge Warlock', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Axion', 'Forge Axion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Bastion', 'Forge Bastion', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Condor', 'Forge Condor', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Dynamo', 'Forge Dynamo', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Everest', 'Forge Everest', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Frost', 'Forge Frost', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Griffin', 'Forge Griffin', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Horizon', 'Forge Horizon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Icarus', 'Forge Icarus', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Jet', 'Forge Jet', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Kinetic', 'Forge Kinetic', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Lumen', 'Forge Lumen', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Mercury', 'Forge Mercury', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Neptune', 'Forge Neptune', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Oxide', 'Forge Oxide', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Pinnacle', 'Forge Pinnacle', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Radiant', 'Forge Radiant', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Stealth', 'Forge Stealth', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Thunder', 'Forge Thunder', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Uppercut', 'Forge Uppercut', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Vortex', 'Forge Vortex', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Wildfire', 'Forge Wildfire', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Xylo', 'Forge Xylo', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Yukon', 'Forge Yukon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Zero', 'Forge Zero', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Alpha', 'Forge Alpha', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Barrage', 'Forge Barrage', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Catalyst', 'Forge Catalyst', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Dispatch', 'Forge Dispatch', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Enigma', 'Forge Enigma', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Firebolt', 'Forge Firebolt', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Garrison', 'Forge Garrison', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Huntsman', 'Forge Huntsman', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Isotope', 'Forge Isotope', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Joker', 'Forge Joker', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Kraken', 'Forge Kraken', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Latitude', 'Forge Latitude', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Monsoon', 'Forge Monsoon', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Nitro', 'Forge Nitro', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Outpost', 'Forge Outpost', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Piston', 'Forge Piston', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Riptide', 'Forge Riptide', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Summit', 'Forge Summit', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Trident', 'Forge Trident', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Uprising', 'Forge Uprising', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Vigil', 'Forge Vigil', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Wyvern', 'Forge Wyvern', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Zodiac', 'Forge Zodiac', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Armada', 'Forge Armada', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Blaze', 'Forge Blaze', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Crusader', 'Forge Crusader', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Domino', 'Forge Domino', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Exodus', 'Forge Exodus', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Foxhound', 'Forge Foxhound', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Gladiator', 'Forge Gladiator', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Harbor', 'Forge Harbor', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Iron', 'Forge Iron', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Juggernaut', 'Forge Juggernaut', FALSE, FALSE, NOW()),
    (gen_random_uuid(), 'Keystone', 'Forge Keystone', FALSE, FALSE, NOW())
ON CONFLICT (codename) DO NOTHING;
