/**
 * startup-config-check.ts — Vacation-Survival Finding A-8
 *
 * Boot-time configuration validation for secrets required by the
 * vacation-survival automation layer and the live-order route.
 *
 * Called from index.ts BEFORE app.listen() — after runPendingMigrations()
 * but before the scheduler starts. Emits WARNs + Discord notifications for
 * missing secrets WITHOUT throwing (never fail-boot on a missing secret — only
 * the missing migration runner failure-mode is allowed to fail boot).
 *
 * Currently checked:
 *   ADMIN_RESTART_HMAC_SECRET
 *     Required by:
 *       - POST /api/admin/self-restart  (auto-restart on dead-man heartbeat)
 *       - POST /api/admin/clear-kill-switch-cache  (A-5 recovery endpoint)
 *       - POST /api/admin/clear-stuck-session      (A-5 recovery endpoint)
 *     If unset: auto-restart is silently disabled and the operator has no
 *     phone-tappable recovery path for stuck states during vacation.
 *
 *   LIVE_ORDER_HMAC_SECRET (Pass 1 Track C)
 *     Required by live-order.ts HMAC signature verification (Path B).
 *     Missing/short → route returns 503 fail-CLOSED on every request.
 *
 *   LIVE_ORDER_GATEWAY_URL (Pass 1 Track C)
 *     Public URL the live-order route uses for self-reference / callback links.
 *     Missing → Path B webhook registration silently produces broken URLs.
 *
 *   TRADING_FORGE_PUBLIC_URL (Pass 1 Track C)
 *     Base URL for outbound links generated by the backend (Discord embeds, etc.).
 *     Missing → those links produce broken placeholder URLs.
 *
 *   SLUMDAWG_WEBHOOK_SECRET (Pass 1 Track C)
 *     Inbound webhook secret for the Slumdawg Discord bot.
 *     Unset OR equal to the known deploy-time placeholder OR shorter than
 *     MIN_SECRET_LENGTH → warn so the operator knows to rotate.
 *
 * Import logger from ./logger.js (not ../index.js) per CLAUDE.md §13 feedback rule.
 */

import { logger } from "./logger.js";
import { appendFamilyGradePostscript } from "./notification-helpers.js";

/** Minimum recommended secret length (32 chars — same as self-restart docs). */
const MIN_SECRET_LENGTH = 32;

/** Known placeholder value shipped in .env.example for SLUMDAWG_WEBHOOK_SECRET. */
const SLUMDAWG_PLACEHOLDER = "slumdawg-rotate-me-after-first-deploy-2026-05-25";

/**
 * Runs boot-time validation of all HMAC/security secrets required by the
 * vacation-survival automation layer and the live-order route.
 *
 * Returns a summary of findings so callers can log or take action.
 * Never throws — all findings are warnings, not hard failures.
 */
export async function checkStartupSecrets(): Promise<{ warnings: string[]; errors: string[] }> {
  const warnings: string[] = [];
  // errors[] is the ERROR-severity channel (vs warnings[]). A missing
  // ADMIN_PROMOTE_HMAC_SECRET is not a soft warning: without it
  // PATCH /api/strategies/:id/lifecycle returns 401 on EVERY call, so no
  // promotion can ever run and the first paper trade can never start — even
  // though the server boots and looks healthy.
  const errors: string[] = [];

  // ── ADMIN_RESTART_HMAC_SECRET ─────────────────────────────────────────────
  const secret = process.env.ADMIN_RESTART_HMAC_SECRET;

  if (!secret || secret.trim().length === 0) {
    const msg =
      "ADMIN_RESTART_HMAC_SECRET is NOT SET. " +
      "Vacation-survival auto-restart (dead-man heartbeat), " +
      "clear-kill-switch-cache, and clear-stuck-session recovery endpoints " +
      "will REJECT all calls in production. " +
      "Set ADMIN_RESTART_HMAC_SECRET (≥32 random chars) in .env before going on vacation.";

    logger.warn(
      {
        env_var: "ADMIN_RESTART_HMAC_SECRET",
        affected_endpoints: [
          "POST /api/admin/self-restart",
          "POST /api/admin/clear-kill-switch-cache",
          "POST /api/admin/clear-stuck-session",
        ],
      },
      `[STARTUP WARN] ${msg}`,
    );

    warnings.push("ADMIN_RESTART_HMAC_SECRET_NOT_SET");

    // Non-blocking Discord notify so the operator learns BEFORE leaving.
    // Fire-and-forget: notification failure must never cause boot to fail.
    try {
      const { notifyWarning } = await import("../services/notification-service.js");
      notifyWarning(
        "ADMIN_RESTART_HMAC_SECRET not configured — vacation-survival disabled",
        appendFamilyGradePostscript(
          msg +
            "\n\nTo fix: add `ADMIN_RESTART_HMAC_SECRET=<random-32-char-string>` to your .env and restart the backend.",
          "A required security setting is missing — Tony's remote-restart and recovery tools are disabled.",
          "No action needed — trading continues normally. Tony should fix this before going on vacation.",
        ),
        { env_var: "ADMIN_RESTART_HMAC_SECRET" },
      );
    } catch (notifyErr) {
      logger.warn({ err: notifyErr }, "startup-config-check: Discord notify failed (non-blocking)");
    }
  } else if (secret.trim().length < MIN_SECRET_LENGTH) {
    const msg =
      `ADMIN_RESTART_HMAC_SECRET is set but SHORTER THAN RECOMMENDED (${secret.trim().length} chars < ${MIN_SECRET_LENGTH}). ` +
      "Endpoints will still accept calls, but short secrets reduce HMAC security. " +
      "Rotate to a ≥32-char random value before going on vacation.";

    logger.warn({ env_var: "ADMIN_RESTART_HMAC_SECRET", length: secret.trim().length }, `[STARTUP WARN] ${msg}`);
    warnings.push("ADMIN_RESTART_HMAC_SECRET_TOO_SHORT");
  }

  // ── LIVE_ORDER_HMAC_SECRET ────────────────────────────────────────────────
  // Required by live-order.ts Path B HMAC verification (live-order.ts:100).
  // Missing or too short → route returns 503 fail-CLOSED on every Pine alert.
  {
    const liveOrderSecret = process.env.LIVE_ORDER_HMAC_SECRET;
    if (!liveOrderSecret || liveOrderSecret.trim().length === 0) {
      const msg =
        "LIVE_ORDER_HMAC_SECRET is NOT SET. " +
        "The live-order route (Path B: Pine → TF gateway → TradersPost) will " +
        "return 503 fail-CLOSED on every inbound Pine alert. " +
        "Set LIVE_ORDER_HMAC_SECRET (≥32 random chars) in .env if you are using Path B.";

      logger.warn(
        { env_var: "LIVE_ORDER_HMAC_SECRET", affected_endpoints: ["POST /api/live-order"] },
        `[STARTUP WARN] ${msg}`,
      );
      warnings.push("LIVE_ORDER_HMAC_SECRET_NOT_SET");
    } else if (liveOrderSecret.trim().length < MIN_SECRET_LENGTH) {
      const msg =
        `LIVE_ORDER_HMAC_SECRET is set but SHORTER THAN RECOMMENDED (${liveOrderSecret.trim().length} chars < ${MIN_SECRET_LENGTH}). ` +
        "The route will accept calls, but short secrets reduce HMAC security. " +
        "Rotate to a ≥32-char random value.";

      logger.warn(
        { env_var: "LIVE_ORDER_HMAC_SECRET", length: liveOrderSecret.trim().length },
        `[STARTUP WARN] ${msg}`,
      );
      warnings.push("LIVE_ORDER_HMAC_SECRET_TOO_SHORT");
    }
  }

  // ── LIVE_ORDER_GATEWAY_URL ────────────────────────────────────────────────
  // Used by live-order.ts for self-reference / callback link generation (Path B).
  // Missing → callback links in Discord notifications and webhook registrations
  // will produce broken placeholder URLs.
  {
    const gatewayUrl = process.env.LIVE_ORDER_GATEWAY_URL;
    if (!gatewayUrl || gatewayUrl.trim().length === 0) {
      const msg =
        "LIVE_ORDER_GATEWAY_URL is NOT SET. " +
        "Path B live-order callback links will produce broken URLs in Discord " +
        "alerts and webhook registrations. " +
        "Set LIVE_ORDER_GATEWAY_URL to the public relay URL (e.g. https://tf-relay-production.up.railway.app).";

      logger.warn({ env_var: "LIVE_ORDER_GATEWAY_URL" }, `[STARTUP WARN] ${msg}`);
      warnings.push("LIVE_ORDER_GATEWAY_URL_NOT_SET");
    }
  }

  // ── TRADING_FORGE_PUBLIC_URL ──────────────────────────────────────────────
  // Base URL used by the backend for outbound links (Discord embeds, etc.).
  // Missing → those links produce broken placeholder URLs.
  {
    const publicUrl = process.env.TRADING_FORGE_PUBLIC_URL;
    if (!publicUrl || publicUrl.trim().length === 0) {
      const msg =
        "TRADING_FORGE_PUBLIC_URL is NOT SET. " +
        "Outbound links generated by the backend (Discord embeds, audit log URLs) " +
        "will produce broken placeholder URLs. " +
        "Set TRADING_FORGE_PUBLIC_URL to the public backend URL.";

      logger.warn({ env_var: "TRADING_FORGE_PUBLIC_URL" }, `[STARTUP WARN] ${msg}`);
      warnings.push("TRADING_FORGE_PUBLIC_URL_NOT_SET");
    }
  }

  // ── SLUMDAWG_WEBHOOK_SECRET ───────────────────────────────────────────────
  // Inbound webhook secret for the Slumdawg Discord bot.
  // Three failure modes: unset, equal to the known deploy-time placeholder,
  // or shorter than the minimum recommended length.
  {
    const slumdawgSecret = process.env.SLUMDAWG_WEBHOOK_SECRET;
    if (!slumdawgSecret || slumdawgSecret.trim().length === 0) {
      const msg =
        "SLUMDAWG_WEBHOOK_SECRET is NOT SET. " +
        "The Slumdawg inbound webhook will silently accept any caller without " +
        "HMAC verification — rotate immediately. " +
        "Set SLUMDAWG_WEBHOOK_SECRET (≥32 random chars) in .env.";

      logger.warn({ env_var: "SLUMDAWG_WEBHOOK_SECRET" }, `[STARTUP WARN] ${msg}`);
      warnings.push("SLUMDAWG_WEBHOOK_SECRET_NOT_SET");
    } else if (slumdawgSecret === SLUMDAWG_PLACEHOLDER) {
      const msg =
        "SLUMDAWG_WEBHOOK_SECRET is still the DEPLOY-TIME PLACEHOLDER value. " +
        "Rotate it immediately — the placeholder is publicly known from .env.example. " +
        "Set SLUMDAWG_WEBHOOK_SECRET to a new ≥32-char random value in .env.";

      logger.warn(
        { env_var: "SLUMDAWG_WEBHOOK_SECRET", reason: "placeholder_value" },
        `[STARTUP WARN] ${msg}`,
      );
      warnings.push("SLUMDAWG_WEBHOOK_SECRET_IS_PLACEHOLDER");
    } else if (slumdawgSecret.trim().length < MIN_SECRET_LENGTH) {
      const msg =
        `SLUMDAWG_WEBHOOK_SECRET is set but SHORTER THAN RECOMMENDED (${slumdawgSecret.trim().length} chars < ${MIN_SECRET_LENGTH}). ` +
        "Rotate to a ≥32-char random value.";

      logger.warn(
        { env_var: "SLUMDAWG_WEBHOOK_SECRET", length: slumdawgSecret.trim().length },
        `[STARTUP WARN] ${msg}`,
      );
      warnings.push("SLUMDAWG_WEBHOOK_SECRET_TOO_SHORT");
    }
  }

  // ── ADMIN_PROMOTE_HMAC_SECRET (Pass 5 Track C) ────────────────────────────
  // Required by PATCH /api/strategies/:id/lifecycle HMAC validation.
  // Missing → route returns 401 on every manual lifecycle transition attempt.
  {
    const promoteSecret = process.env.ADMIN_PROMOTE_HMAC_SECRET;
    if (!promoteSecret || promoteSecret.trim().length === 0) {
      const msg =
        "ADMIN_PROMOTE_HMAC_SECRET is NOT SET. " +
        "PATCH /api/strategies/:id/lifecycle will reject all calls with HTTP 401 — " +
        "NO promotion is possible, so the first paper trade can never start. " +
        "Set ADMIN_PROMOTE_HMAC_SECRET (≥32 random chars) in .env to enable manual lifecycle transitions.";
      // ERROR severity is carried by the errors[] return channel (vs warnings[]);
      // the log line stays on logger.warn (the file's single log convention) but is
      // tagged [STARTUP ERROR] so the level is unambiguous in the boot log.
      logger.warn({ env_var: "ADMIN_PROMOTE_HMAC_SECRET", affected_endpoints: ["PATCH /api/strategies/:id/lifecycle"] }, `[STARTUP ERROR] ${msg}`);
      errors.push("ADMIN_PROMOTE_HMAC_SECRET_NOT_SET");
    } else if (promoteSecret.trim().length < MIN_SECRET_LENGTH) {
      logger.warn({ env_var: "ADMIN_PROMOTE_HMAC_SECRET", length: promoteSecret.trim().length }, `[STARTUP WARN] ADMIN_PROMOTE_HMAC_SECRET is set but shorter than recommended (${promoteSecret.trim().length} < ${MIN_SECRET_LENGTH}).`);
      warnings.push("ADMIN_PROMOTE_HMAC_SECRET_TOO_SHORT");
    }
  }

  // ── KASA_* remote power-cycle escape valve (Pass 7 Track B) ──────────────
  // Optional feature: TP-Link Kasa smart-plug power-cycle when the dead-man's
  // heartbeat 24h auto-restart cap is reached. All three vars must be set
  // together. Partial config (only some set) is worse than none because it
  // creates a false impression that the escape valve is active when the service
  // will actually fail at invocation time.
  {
    const kasaIp       = process.env["KASA_DEVICE_IP"];
    const kasaUser     = process.env["KASA_USERNAME"];
    const kasaPassword = process.env["KASA_PASSWORD"];

    const kasaVarsSet = [
      kasaIp       ? "KASA_DEVICE_IP"  : null,
      kasaUser     ? "KASA_USERNAME"   : null,
      kasaPassword ? "KASA_PASSWORD"   : null,
    ].filter(Boolean) as string[];

    const kasaVarsMissing = [
      kasaIp       ? null : "KASA_DEVICE_IP",
      kasaUser     ? null : "KASA_USERNAME",
      kasaPassword ? null : "KASA_PASSWORD",
    ].filter(Boolean) as string[];

    if (kasaVarsSet.length > 0 && kasaVarsMissing.length > 0) {
      // Partial config — this is the dangerous case.
      const msg =
        `KASA remote power-cycle is PARTIALLY configured. ` +
        `Set: [${kasaVarsSet.join(", ")}]. ` +
        `Missing: [${kasaVarsMissing.join(", ")}]. ` +
        `The escape valve will FAIL at invocation time (dead-man's heartbeat 4th-attempt) ` +
        `because the script requires all three vars. ` +
        `Either set ALL three (KASA_DEVICE_IP, KASA_USERNAME, KASA_PASSWORD) to enable ` +
        `the escape valve, or leave all three unset to preserve the existing terminal-action alert.`;

      logger.warn(
        {
          kasa_vars_set: kasaVarsSet,
          kasa_vars_missing: kasaVarsMissing,
        },
        `[STARTUP WARN] ${msg}`,
      );
      warnings.push("KASA_PARTIAL_CONFIG");

      try {
        const { notifyWarning } = await import("../services/notification-service.js");
        notifyWarning(
          "KASA remote power-cycle partially configured — escape valve will fail",
          appendFamilyGradePostscript(
            msg + "\n\nTo fix: set all three KASA_* vars in .env and restart the backend.",
            "The smart-plug remote-restart feature is partially set up and will not work if needed.",
            "No action needed — trading continues normally. Tony needs to finish the smart-plug setup.",
          ),
          { kasa_vars_set: kasaVarsSet, kasa_vars_missing: kasaVarsMissing },
        );
      } catch (notifyErr) {
        logger.warn({ err: notifyErr }, "startup-config-check: Discord notify failed (non-blocking)");
      }
    } else if (kasaVarsSet.length === 3) {
      logger.info(
        { kasa_device_ip: kasaIp },
        "startup-config-check: KASA remote power-cycle escape valve is ACTIVE",
      );
    }
    // kasaVarsSet.length === 0 → escape valve disabled intentionally (no warning needed)
  }

  // ── broker_accounts credentials (Deep-Scan H13) ──────────────────────────
  // Surface a missing-broker-credentials gap at BOOT instead of at first-order
  // routing time — broker-router throws there AFTER partial journal state is
  // written, which is far harder to recover from. Non-fatal (warn-only) and
  // fail-soft: a transient DB error at boot must never crash the process.
  // db/schema are dynamically imported (not top-level) so this check never
  // perturbs test isolation per feedback_helper_logger_import.md.
  {
    try {
      const { db } = await import("../db/index.js");
      const { brokerAccounts, instanceConfig } = await import("../db/schema.js");
      const { eq } = await import("drizzle-orm");

      const enabledAccounts = await db
        .select()
        .from(brokerAccounts)
        .where(eq(brokerAccounts.enabled, true));

      // (a) Every firm in the instance allow-list must have ≥1 enabled account.
      const cfgRows = await db.select().from(instanceConfig).limit(1);
      const allowList: string[] = Array.isArray(cfgRows[0]?.enabledFirms)
        ? (cfgRows[0]!.enabledFirms as string[])
        : [];
      const enabledFirmIds = new Set(enabledAccounts.map((a) => a.firmId));
      const firmsWithoutAccount = allowList.filter((firm) => !enabledFirmIds.has(firm));

      if (allowList.length > 0 && firmsWithoutAccount.length > 0) {
        const msg =
          `No enabled broker_accounts row for allow-listed firm(s): [${firmsWithoutAccount.join(", ")}]. ` +
          "Order routing for these firms will THROW at first signal (after partial journal state is written). " +
          "Seed an enabled broker_accounts row per firm before going live.";
        logger.warn(
          { firms_without_account: firmsWithoutAccount, allow_list: allowList },
          `[STARTUP WARN] ${msg}`,
        );
        warnings.push("BROKER_ACCOUNT_MISSING_FOR_ENABLED_FIRM");
      }

      // (b) Any enabled account whose apiKeyVaultRef points at an undefined env var.
      const missingVaultEnv = enabledAccounts
        .filter(
          (a) =>
            a.apiKeyVaultRef != null &&
            a.apiKeyVaultRef.trim().length > 0 &&
            process.env[a.apiKeyVaultRef] === undefined,
        )
        .map((a) => ({ account_id: a.accountId, firm_id: a.firmId, vault_ref: a.apiKeyVaultRef }));

      if (missingVaultEnv.length > 0) {
        const msg =
          `${missingVaultEnv.length} enabled broker_accounts row(s) reference an apiKeyVaultRef ` +
          `whose env var is UNDEFINED: [${missingVaultEnv.map((m) => m.vault_ref).join(", ")}]. ` +
          "Broker auth will fail at order-routing time. Set the referenced env var(s) in .env.";
        logger.warn({ missing_vault_env: missingVaultEnv }, `[STARTUP WARN] ${msg}`);
        warnings.push("BROKER_ACCOUNT_VAULT_ENV_UNDEFINED");
      }
    } catch (brokerErr) {
      // Fail-soft: a DB hiccup at boot must never crash. Log and move on.
      logger.warn(
        { err: brokerErr },
        "startup-config-check: broker_accounts credential check skipped (query failed)",
      );
    }
  }

  if (errors.length > 0) {
    logger.warn(
      { errors },
      "[STARTUP ERROR] startup-config-check: ERROR-severity config problems detected — fix before promoting any strategy",
    );
  }

  if (warnings.length === 0 && errors.length === 0) {
    logger.info(
      {
        checked: [
          "ADMIN_RESTART_HMAC_SECRET",
          "LIVE_ORDER_HMAC_SECRET",
          "LIVE_ORDER_GATEWAY_URL",
          "TRADING_FORGE_PUBLIC_URL",
          "SLUMDAWG_WEBHOOK_SECRET",
          "ADMIN_PROMOTE_HMAC_SECRET",
          "KASA_DEVICE_IP/KASA_USERNAME/KASA_PASSWORD",
          "broker_accounts (enabled rows + vault env)",
        ],
      },
      "startup-config-check: all required secrets configured",
    );
  }

  return { warnings, errors };
}
