"""AR-1393 — emit the complete SHA-256 manifest for every committed E8 visual artifact.

AR-1383A section 7 item 6: "Either add SHA-256 values for all 26 committed visual artifacts or
correct the claim that all 26 are listed." AR-1392's findings file hashed only the frames it
argued from, while its prose implied the whole set was listed. This generates the full set so the
claim and the evidence match, and so any later drift in a frame is detectable.

Run:  python scripts/_worker_vi_e8_hash_manifest.py
Writes artifact-manifest.sha256 beside the frames directory.
"""

import hashlib
import os

BASE = ("docs/replay-results/gpt-engineering/opus-transcript-first-diagnostic/"
        "visual-intelligence-e8-round1/E8Wg6tFPYjo")
FRAMES = os.path.join(BASE, "frames")
OUT = os.path.join(BASE, "artifact-manifest.sha256")


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


names = sorted(n for n in os.listdir(FRAMES) if n.lower().endswith(".png"))
lines = [f"{sha256_file(os.path.join(FRAMES, n))}  frames/{n}" for n in names]

with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("# SHA-256 manifest -- every committed visual artifact for E8Wg6tFPYjo.\n")
    fh.write("# Generated by scripts/_worker_vi_e8_hash_manifest.py (AR-1393).\n")
    fh.write(f"# {len(names)} artifacts. Verify with:  sha256sum -c artifact-manifest.sha256\n")
    fh.write("\n".join(lines) + "\n")

print(f"{len(names)} artifacts hashed -> {OUT}")
for line in lines:
    print("  " + line)
