"""AR-1394 — the E8 visual artifact manifest, with PORTABLE and LOCAL identity separated.

AR-1383A section 7 item 6 required SHA-256 for every committed visual artifact. AR-1393 delivered
that over encoded PNG bytes only, and AR-1384A section 5 then measured the consequence on a clean
checkout under a different Pillow build: regenerating the magnifications rewrote five files that
nobody had edited, and the byte manifest failed on all five.

THE FIX IS NOT A LOOSER CHECK. It is two checks that mean different things:

    PIXELS  sha256 over the decoded RGB buffer + dimensions
            -> CONTENT identity. Survives a re-encode under a different zlib/Pillow build.
            -> This is the PORTABLE claim, and the only one the reproducibility test asserts.

    BYTES   sha256 over the encoded file
            -> EXACT-FILE identity. Detects any change at all, including a benign re-encode.
            -> Recorded and checked, but NEVER claimed portable across environments.

AR-1393 proved idempotence in ONE environment and reported it as reproducibility. That over-scoped
claim is withdrawn; the honest claim is pixel-level reproducibility plus environment-local byte
stability, and the two are now labelled separately so neither borrows the other's authority.

Run:  python scripts/_worker_vi_e8_hash_manifest.py           regenerate the manifest
      python scripts/_worker_vi_e8_hash_manifest.py --verify  check disk against the manifest
"""

import hashlib
import os
import sys

from PIL import Image

BASE = ("docs/replay-results/gpt-engineering/opus-transcript-first-diagnostic/"
        "visual-intelligence-e8-round1/E8Wg6tFPYjo")
FRAMES = os.path.join(BASE, "frames")
OUT = os.path.join(BASE, "artifact-manifest.sha256")


def byte_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def pixel_sha256(path):
    """Encoder-independent identity: the decoded RGB buffer plus its dimensions."""
    rgb = Image.open(path).convert("RGB")
    h = hashlib.sha256()
    h.update(f"{rgb.width}x{rgb.height}|".encode())
    h.update(rgb.tobytes())
    return h.hexdigest()


def rows():
    names = sorted(n for n in os.listdir(FRAMES) if n.lower().endswith(".png"))
    return [(n, byte_sha256(os.path.join(FRAMES, n)), pixel_sha256(os.path.join(FRAMES, n)))
            for n in names]


def write_manifest():
    data = rows()
    lines = [
        "# SHA-256 manifest -- every committed visual artifact for E8Wg6tFPYjo.",
        "# Generated by scripts/_worker_vi_e8_hash_manifest.py (AR-1394, on AR-1384A section 5).",
        f"# {len(data)} artifacts.",
        "#",
        "# TWO IDENTITIES PER ARTIFACT, and they do NOT mean the same thing:",
        "#   PIXELS = sha256(decoded RGB buffer + dimensions).  CONTENT identity. PORTABLE across",
        "#            Pillow/zlib builds. This is what the reproducibility test asserts.",
        "#   BYTES  = sha256(encoded file).  EXACT-FILE identity. Environment-LOCAL: a benign",
        "#            re-encode under a different build changes it without changing the image.",
        "#",
        "# Verify:  python scripts/_worker_vi_e8_hash_manifest.py --verify",
        "#          (sha256sum -c also works but checks BYTES only -- the non-portable half.)",
        "",
    ]
    for name, b, p in data:
        lines.append(f"{b}  frames/{name}")
        lines.append(f"# PIXELS {p}  frames/{name}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"{len(data)} artifacts hashed -> {OUT}")
    for name, b, p in data:
        print(f"  BYTES  {b}  frames/{name}")
        print(f"  PIXELS {p}")


def parse_manifest():
    byte_map, pixel_map = {}, {}
    for line in open(OUT, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("# PIXELS "):
            _, _, digest, name = line.split(None, 3)
            pixel_map[name] = digest
        elif line and not line.startswith("#"):
            digest, name = line.split(None, 1)
            byte_map[name.strip()] = digest
    return byte_map, pixel_map


def verify():
    byte_map, pixel_map = parse_manifest()
    on_disk = {f"frames/{n}" for n in os.listdir(FRAMES) if n.lower().endswith(".png")}

    missing = sorted(set(byte_map) - on_disk)
    unlisted = sorted(on_disk - set(byte_map))
    pixel_bad, byte_bad = [], []

    for rel in sorted(set(byte_map) & on_disk):
        path = os.path.join(BASE, rel)
        if pixel_sha256(path) != pixel_map.get(rel):
            pixel_bad.append(rel)
        if byte_sha256(path) != byte_map[rel]:
            byte_bad.append(rel)

    print(f"artifacts listed {len(byte_map)}, on disk {len(on_disk)}")
    for rel in missing:
        print(f"  MISSING   {rel}")
    for rel in unlisted:
        print(f"  UNLISTED  {rel}")
    for rel in byte_bad:
        print(f"  BYTES differ  {rel}" + ("  (pixels OK -- benign re-encode)"
                                          if rel not in pixel_bad else ""))
    for rel in pixel_bad:
        print(f"  PIXELS DIFFER {rel}   <-- CONTENT CHANGED")

    print()
    if missing or unlisted or pixel_bad:
        print("FAIL: content integrity is broken.")
        return 1
    if byte_bad:
        print(f"PASS (PORTABLE): all {len(byte_map)} artifacts match by decoded pixels.")
        print(f"NOTE: {len(byte_bad)} file(s) differ in encoded bytes only -- expected when the "
              f"image library differs from the one that generated the manifest. Content is intact.")
        return 0
    print(f"PASS (EXACT): all {len(byte_map)} artifacts match by BOTH pixels and bytes.")
    return 0


if __name__ == "__main__":
    sys.exit(verify() if "--verify" in sys.argv else (write_manifest() or 0))
