<#
  INSTALL THE WORKER-2 SEAT ENTRYPOINT -- mirrors scripts/install_worker1_seat_shortcut.ps1.

  Produces the single action the operator takes to seat Worker 2:

      Desktop\"Claude Code - Worker 2.lnk"
          -> <container>\worker2-seat.ps1          (resolver, generated by this script)
              -> <canonical worktree>\scripts\worker2_seat_launch.ps1   (checks + launch)

  Same reasoning as Worker 1's installer: a resolver file (not a long shortcut argument) keeps
  the resolution logic in versioned git text; a separate shortcut (not a repointed one) leaves
  "Claude Code - Trading Forge" untouched for every other lane; the worktree is resolved by
  BRANCH PATTERN through `git worktree list`, never baked as a dated path.

  Re-runnable. Overwrites its own two generated artifacts and nothing else.
#>

$ErrorActionPreference = 'Stop'

$Worktree = Split-Path -Parent $PSScriptRoot

$porcelain = & git -C $Worktree worktree list --porcelain
$PrimaryRepo = ($porcelain | Select-Object -First 1) -replace '^worktree\s+', ''
$PrimaryRepo = $PrimaryRepo -replace '/', '\'
if (-not (Test-Path (Join-Path $PrimaryRepo '.git'))) {
  throw "resolved primary repo '$PrimaryRepo' does not look like a repository root"
}

$Container = Split-Path -Parent $PrimaryRepo
$ResolverPath = Join-Path $Container 'worker2-seat.ps1'
$Desktop = [Environment]::GetFolderPath('Desktop')
$LinkPath = Join-Path $Desktop 'Claude Code - Worker 2.lnk'

$resolver = @"
# GENERATED by scripts/install_worker2_seat_shortcut.ps1. Do not hand-edit -- re-run the
# installer instead. Canonical source lives in the Worker-2 worktree, in git.
`$ErrorActionPreference = 'Stop'
`$PrimaryRepo  = '$PrimaryRepo'
`$BranchGlob   = 'refs/heads/claude/worker2-*'

`$found = @()
`$current = `$null
foreach (`$line in (& git -C `$PrimaryRepo worktree list --porcelain)) {
  if (`$line -like 'worktree *') { `$current = `$line -replace '^worktree\s+', '' }
  elseif (`$line -like 'branch *') {
    `$b = `$line -replace '^branch\s+', ''
    if (`$b -like `$BranchGlob) { `$found += (`$current -replace '/', '\') }
  }
}

if (`$found.Count -ne 1) {
  Write-Host ''
  Write-Host '  WORKER-2 SEAT REFUSED TO START.' -ForegroundColor Red
  Write-Host "  Expected exactly one worktree on `$BranchGlob, found `$(`$found.Count)." -ForegroundColor Red
  foreach (`$f in `$found) { Write-Host "    `$f" -ForegroundColor Red }
  Write-Host ''
  Write-Host '  This is an engineering fault. Start Claude normally and paste these lines.'
  Write-Host ''
  exit 1
}

& (Join-Path `$found[0] 'scripts\worker2_seat_launch.ps1') @args
"@

[System.IO.File]::WriteAllText($ResolverPath, $resolver, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "resolver  -> $ResolverPath"

foreach ($target in @($ResolverPath, (Join-Path $Worktree 'scripts\worker2_seat_launch.ps1'))) {
  $perr = $null; $ptok = $null
  [System.Management.Automation.Language.Parser]::ParseFile($target, [ref]$ptok, [ref]$perr) | Out-Null
  if ($perr.Count -gt 0) {
    throw "refusing to install: $target has $($perr.Count) parse error(s), first at line $($perr[0].Extent.StartLineNumber): $($perr[0].Message)"
  }
  $nonAscii = @([System.IO.File]::ReadAllBytes($target) | Where-Object { $_ -gt 127 }).Count
  if ($nonAscii -gt 0) {
    throw "refusing to install: $target has $nonAscii non-ASCII byte(s); keep launcher scripts ASCII so encoding cannot break the parse"
  }
}

$shell = New-Object -ComObject WScript.Shell
$lnk = $shell.CreateShortcut($LinkPath)
$lnk.TargetPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$lnk.Arguments = "-NoExit -ExecutionPolicy Bypass -File `"$ResolverPath`""
$lnk.WorkingDirectory = $Container
$lnk.IconLocation = "$($lnk.TargetPath),0"
$lnk.Description = 'Seat Worker 2 in the governed worktree.'
$lnk.Save()
Write-Host "shortcut  -> $LinkPath"

Write-Host ''
Write-Host 'Installed. Worker 2 is now one double-click, with no directory to remember.'
