<#
  INSTALL THE WORKER-1 SEAT ENTRYPOINT -- AR-1271A sec 4.

  Produces the single action the operator takes to seat Worker 1:

      Desktop\"Claude Code - Worker 1.lnk"
          -> <container>\worker1-seat.ps1          (resolver, generated by this script)
              -> <canonical worktree>\scripts\worker1_seat_launch.ps1   (checks + launch)

  WHY A RESOLVER FILE AND NOT A LONGER SHORTCUT ARGUMENT
    The shortcut cannot contain the resolution logic, because a nested-quoted PowerShell
    one-liner inside a .lnk is exactly the kind of quoting this desk has been burned by before,
    and it would be unreviewable and unversioned. The resolver is generated from THIS committed
    file, so the canonical source stays in git and the generated copy can always be rebuilt.

  WHY A SEPARATE SHORTCUT AND NOT A REPOINTED ONE
    "Claude Code - Trading Forge" is used for every lane, not just Worker 1. Repointing it at the
    Worker-1 worktree would hijack Worker-2, advisor and general sessions. This script therefore
    ADDS an entrypoint and leaves the existing shortcut untouched. Least invasive (AR-1271A sec 4).

  WHY THE WORKTREE IS RESOLVED, NOT BAKED
    Worker-1 worktrees are dated and get replaced (AR-1271A sec 4.3). Only the PRIMARY REPO path is
    baked, and that one is structural rather than temporary. The seat worktree is found through
    `git worktree list` by BRANCH PATTERN, so the next dated worktree is picked up with no edit
    here. If the pattern matches anything other than exactly one worktree, the resolver refuses
    rather than guessing -- an ambiguous seat is how the wrong tree gets worked in.

  Re-runnable. Overwrites its own two generated artifacts and nothing else.
#>

$ErrorActionPreference = 'Stop'

$Worktree = Split-Path -Parent $PSScriptRoot

# The primary worktree is the first record of `worktree list` and is the non-dated repo root.
$porcelain = & git -C $Worktree worktree list --porcelain
$PrimaryRepo = ($porcelain | Select-Object -First 1) -replace '^worktree\s+', ''
$PrimaryRepo = $PrimaryRepo -replace '/', '\'
if (-not (Test-Path (Join-Path $PrimaryRepo '.git'))) {
  throw "resolved primary repo '$PrimaryRepo' does not look like a repository root"
}

$Container = Split-Path -Parent $PrimaryRepo
$ResolverPath = Join-Path $Container 'worker1-seat.ps1'
$Desktop = [Environment]::GetFolderPath('Desktop')
$LinkPath = Join-Path $Desktop 'Claude Code - Worker 1.lnk'

# --- the generated resolver ------------------------------------------------------------------
$resolver = @"
# GENERATED by scripts/install_worker1_seat_shortcut.ps1 (AR-1271A sec 4). Do not hand-edit --
# re-run the installer instead. Canonical source lives in the Worker-1 worktree, in git.
`$ErrorActionPreference = 'Stop'
`$PrimaryRepo  = '$PrimaryRepo'
`$BranchGlob   = 'refs/heads/claude/worker1-h1-*'

# Resolve the canonical Worker-1 seat worktree by branch pattern. Never a dated path.
`$found = @()
`$current = `$null
foreach (`$line in (& git -C `$PrimaryRepo worktree list --porcelain)) {
  if (`$line -like 'worktree *') { `$current = `$line -replace '^worktree\s+', '' }
  elseif (`$line -like 'branch *') {
    `$b = `$line -replace '^branch\s+', ''
    if (`$b -like `$BranchGlob) { `$found += (`$current -replace '/', '\') }
  }
}

if (`$found.Count -ne 1) {
  Write-Host ''
  Write-Host '  WORKER-1 SEAT REFUSED TO START.' -ForegroundColor Red
  Write-Host "  Expected exactly one worktree on `$BranchGlob, found `$(`$found.Count)." -ForegroundColor Red
  foreach (`$f in `$found) { Write-Host "    `$f" -ForegroundColor Red }
  Write-Host ''
  Write-Host '  This is an engineering fault. Start Claude normally and paste these lines.'
  Write-Host ''
  exit 1
}

& (Join-Path `$found[0] 'scripts\worker1_seat_launch.ps1') @args
"@

# Written ASCII with NO BOM. `Set-Content -Encoding utf8` on PowerShell 5.1 prepends a 3-byte BOM,
# which the ASCII check below correctly rejects -- caught by that check on its first run.
[System.IO.File]::WriteAllText($ResolverPath, $resolver, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "resolver  -> $ResolverPath"

# --- refuse to install an entrypoint that cannot run -------------------------------------------
# MEASURED 2026-08-16: the launcher was first written UTF-8 with no BOM, and PowerShell 5.1 read
# its em-dashes as CP1252 -- which manufactures 8 smart double-quotes and breaks the parse. The
# reported symptom was a missing brace on a line whose braces were correct. Nothing about that is
# visible by reading the file, so it is checked mechanically here rather than trusted.
# `AN ENTRYPOINT THAT FAILS ONLY WHEN DOUBLE-CLICKED HAS NO OTHER OBSERVER.`
foreach ($target in @($ResolverPath, (Join-Path $Worktree 'scripts\worker1_seat_launch.ps1'))) {
  $perr = $null; $ptok = $null
  [System.Management.Automation.Language.Parser]::ParseFile($target, [ref]$ptok, [ref]$perr) | Out-Null
  if ($perr.Count -gt 0) {
    throw "refusing to install: $target has $($perr.Count) parse error(s), first at line $($perr[0].Extent.StartLineNumber): $($perr[0].Message)"
  }
  $nonAscii = @([System.IO.File]::ReadAllBytes($target) | Where-Object { $_ -gt 127 }).Count
  if ($nonAscii -gt 0) {
    throw "refusing to install: $target has $nonAscii non-ASCII byte(s); keep launcher scripts ASCII so encoding cannot break the parse"
  }
}

# --- the shortcut -----------------------------------------------------------------------------
$shell = New-Object -ComObject WScript.Shell
$lnk = $shell.CreateShortcut($LinkPath)
$lnk.TargetPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$lnk.Arguments = "-NoExit -ExecutionPolicy Bypass -File `"$ResolverPath`""
$lnk.WorkingDirectory = $Container
$lnk.IconLocation = "$($lnk.TargetPath),0"
$lnk.Description = 'Seat Worker 1 in the governed worktree (refuses to start unbound).'
$lnk.Save()
Write-Host "shortcut  -> $LinkPath"

Write-Host ''
Write-Host 'Installed. Worker 1 is now one double-click, with no directory to remember.'
