"""
test_session_windows_parity.py — THE TEST `session_windows.py` HAS BEEN CITING.

R-315 §4. `src/engine/session_windows.py` stated in its module docstring that
"Parity is enforced by test_session_windows_parity.py" and used that parity as
the stated reason the module is NOT flagged ``approximation=True``. THAT FILE DID
NOT EXIST, and no cross-runtime test existed under any other name: the
de-approximation rested on a guarantee whose named enforcer was absent. This file
makes the citation true.

WHAT IS MEASURED: for every instant in the fixture, the five killzone booleans
produced by THIS module are compared against the answers produced by the REAL
``src/server/lib/killzone.ts``. Neither side is reimplemented here — the TS
answers were generated by importing the production module (see
``generate_session_windows_parity_fixture.py``) and frozen, because a pytest that
shells out to Node is unrunnable where Node is absent and a test that silently
SKIPS is a non-biter.

WHAT KEEPS IT FROM GOING STALE: the fixture records the sha256 of killzone.ts and
this test asserts it still matches the live file. A change to killzone.ts fails
this test with an instruction to regenerate, so the fixture can never keep
reporting parity against a version of the file that no longer exists.

FIRST MEASURED RESULT (2026-07-28): 5,826 instants over four ET days including
BOTH DST transitions, 40,782 comparisons, ZERO mismatches — and the comparison
was red-proved by shifting single boundary constants by one minute, which
produced 8 and 6 mismatches respectively.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path

import pytest

from src.engine import session_windows as sw

REPO = Path(__file__).resolve().parents[3]
KILLZONE_TS = REPO / "src" / "server" / "lib" / "killzone.ts"
FIXTURE_PATH = Path(__file__).parent / "fixtures" / "session_windows_parity.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    assert FIXTURE_PATH.exists(), (
        f"missing {FIXTURE_PATH} — regenerate with "
        "python src/engine/tests/generate_session_windows_parity_fixture.py"
    )
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _py_bits(instant: str, zones: list[str]) -> str:
    dt = datetime.fromisoformat(instant)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return "".join("1" if sw.is_in_killzone(dt, z) else "0" for z in zones)


def test_fixture_is_current_with_killzone_ts(fixture: dict) -> None:
    """The frozen TS answers must describe the killzone.ts that exists NOW.

    Without this the fixture is an artifact-staleness hazard: it would keep
    reporting parity against a file that had since changed.
    """
    live = hashlib.sha256(KILLZONE_TS.read_bytes()).hexdigest()
    assert live == fixture["killzone_ts_sha256"], (
        "killzone.ts has changed since this fixture was generated — parity is "
        "UNVERIFIED until you re-run "
        "python src/engine/tests/generate_session_windows_parity_fixture.py\n"
        f"  fixture: {fixture['killzone_ts_sha256']}\n  live   : {live}"
    )


def test_python_and_typescript_agree_on_every_instant(fixture: dict) -> None:
    """Exhaustive. No threshold, no sampling, no tolerance."""
    zones = fixture["zones"]
    mismatches: list[str] = []
    for instant, ts_bits in fixture["answers"].items():
        py_bits = _py_bits(instant, zones)
        if py_bits != ts_bits:
            mismatches.append(f"{instant}: py={py_bits} ts={ts_bits}")
    assert not mismatches, (
        f"{len(mismatches)} cross-runtime disagreements "
        f"(of {len(fixture['answers'])} instants); first 10:\n  "
        + "\n  ".join(mismatches[:10])
    )


def test_fixture_is_not_degenerate(fixture: dict) -> None:
    """A control: a fixture where every answer is False would pass vacuously."""
    answers = fixture["answers"].values()
    inside = sum(1 for bits in answers if "1" in bits)
    assert inside > 0, "no instant falls inside ANY zone — the fixture proves nothing"
    # Every zone must be exercised, or that zone's parity is untested.
    for idx, zone in enumerate(fixture["zones"]):
        hits = sum(1 for bits in answers if bits[idx] == "1")
        assert hits > 0, f"zone {zone!r} is never active in the fixture — untested"


def test_both_dst_transition_days_are_covered(fixture: dict) -> None:
    """DST is where two IANA-backed implementations most plausibly diverge."""
    assert "2026-03-08" in fixture["days"], "spring-forward day missing"
    assert "2026-11-01" in fixture["days"], "fall-back day missing"


def test_comparison_bites_when_a_boundary_moves(fixture: dict) -> None:
    """RED-PROOF. A parity test that cannot fail is worth nothing.

    Shift one boundary constant by one minute and the comparison must report
    disagreements; restore it and the count must return to zero.
    """
    zones = fixture["zones"]

    def count_mismatches() -> int:
        return sum(
            1
            for instant, ts_bits in fixture["answers"].items()
            if _py_bits(instant, zones) != ts_bits
        )

    assert count_mismatches() == 0, "baseline must be clean before mutating"

    original = sw.NY_AM_START_MIN
    try:
        sw.NY_AM_START_MIN = original + 1
        assert count_mismatches() > 0, (
            "shifting NY_AM_START by one minute produced NO disagreement — the "
            "comparison does not bite and this whole file is decorative"
        )
    finally:
        sw.NY_AM_START_MIN = original

    assert count_mismatches() == 0, "constant not restored after the red-proof"
